# This file was auto-generated by Polybuild

ifndef OS
	OS := $(shell uname)
endif

obj_ext := .o
ifeq ($(OS),Windows_NT)
	obj_ext := .obj
	out_ext := .exe
endif

compiler := $(CXX)
compilation_flags := -Wall -std=c++17 -O3
libraries := -ldpp -lssl -lcrypto

default: quran-bot$(out_ext)
.PHONY: default

obj/main_0$(obj_ext): ./main.cpp
	@printf '\033[1m[POLYBUILD]\033[0m Compiling $@ from $<...\n'
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished compiling $@ from $<!\n'

quran-bot$(out_ext): obj/main_0$(obj_ext)
	@printf '\033[1m[POLYBUILD]\033[0m Building $@...\n'
	@$(compiler) $^ $(static_libraries) $(compilation_flags) $(libraries) -o $@
	@printf '\033[1m[POLYBUILD]\033[0m Finished building $@!\n'

clean:
	@printf '\033[1m[POLYBUILD]\033[0m Deleting quran-bot$(out_ext) and obj...\n'
	@rm -rf quran-bot$(out_ext) obj
	@printf '\033[1m[POLYBUILD]\033[0m Finished deleting quran-bot$(out_ext) and obj!\n'
.PHONY: clean
